name = "fpm_test_exit_code"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2023, Jane Doe"
[build]
auto-executables = true
[install]
library = false
